class InsertDataPrueba < ActiveRecord::Migration[5.0]
  def change
	CategoriaServicio.create(codigo: 'CAT-1', nombre: 'Consulta Medica', estatus: 'A');
	CategoriaServicio.create(codigo: 'CAT-2', nombre: 'Laboratorio', estatus: 'A');
	CategoriaServicio.create(codigo: 'CAT-3', nombre: 'Imagenologia', estatus: 'A');

	Especialidad.create(codigo: 'ESP-1', categoria_servicio_id: 1, nombre: 'Cardiologia', estatus: 'A');
	Especialidad.create(codigo: 'ESP-2', categoria_servicio_id: 1, nombre: 'Dermatologia', estatus: 'A');
	Especialidad.create(codigo: 'ESP-3', categoria_servicio_id: 1, nombre: 'Pediatria', estatus: 'A');
	Especialidad.create(codigo: 'ESP-4', categoria_servicio_id: 1, nombre: 'Endocrinologia', estatus: 'A');
	Especialidad.create(codigo: 'ESP-5', categoria_servicio_id: 1, nombre: 'Gastroenterologia', estatus: 'A');
	Especialidad.create(codigo: 'ESP-6', categoria_servicio_id: 1, nombre: 'Nefrologia', estatus: 'A');
	Especialidad.create(codigo: 'ESP-7', categoria_servicio_id: 1, nombre: 'Neurologia', estatus: 'A');
	Especialidad.create(codigo: 'ESP-8', categoria_servicio_id: 1, nombre: 'Nutriologia', estatus: 'A');
	Especialidad.create(codigo: 'ESP-9', categoria_servicio_id: 1, nombre: 'Oftalmologia', estatus: 'A');
	Especialidad.create(codigo: 'ESP-10', categoria_servicio_id: 1, nombre: 'Urologia', estatus: 'A');
	Especialidad.create(codigo: 'ESP-11', categoria_servicio_id: 2, nombre: 'Analisis de Sangre', estatus: 'A');
	Especialidad.create(codigo: 'ESP-12', categoria_servicio_id: 2, nombre: 'Analisis de Orina', estatus: 'A');
	Especialidad.create(codigo: 'ESP-13', categoria_servicio_id: 2, nombre: 'Analisis de Heces', estatus: 'A');
	Especialidad.create(codigo: 'ESP-14', categoria_servicio_id: 2, nombre: 'Colesterol', estatus: 'A');
	Especialidad.create(codigo: 'ESP-15', categoria_servicio_id: 2, nombre: 'Glucosa', estatus: 'A');
	Especialidad.create(codigo: 'ESP-16', categoria_servicio_id: 2, nombre: 'Transaminasas', estatus: 'A');
	Especialidad.create(codigo: 'ESP-17', categoria_servicio_id: 2, nombre: 'Hemograma', estatus: 'A');
	Especialidad.create(codigo: 'ESP-18', categoria_servicio_id: 3, nombre: 'Radiologia', estatus: 'A');
	Especialidad.create(codigo: 'ESP-19', categoria_servicio_id: 3, nombre: 'Tomografia', estatus: 'A');
	Especialidad.create(codigo: 'ESP-20', categoria_servicio_id: 3, nombre: 'Ecografia', estatus: 'A');
	Especialidad.create(codigo: 'ESP-21', categoria_servicio_id: 3, nombre: 'Mamografia', estatus: 'A');
	Especialidad.create(codigo: 'ESP-22', categoria_servicio_id: 3, nombre: 'Resonancia Magnetica', estatus: 'A');

	Servicio.create(codigo: 'SER-1', especialidad_id: 1, nombre: 'Consulta Medica en Cardiologia', estatus: 'A');
	Servicio.create(codigo: 'SER-2', especialidad_id: 2, nombre: 'Consulta Medica en Dermatologia', estatus: 'A');
	Servicio.create(codigo: 'SER-3', especialidad_id: 3, nombre: 'Consulta Medica en Pediatria', estatus: 'A');
	Servicio.create(codigo: 'SER-4', especialidad_id: 4, nombre: 'Consulta Medica en Endocrinologia', estatus: 'A');
	Servicio.create(codigo: 'SER-5', especialidad_id: 5, nombre: 'Consulta Medica en Gastroenterologia', estatus: 'A');
	Servicio.create(codigo: 'SER-6', especialidad_id: 6, nombre: 'Consulta Medica en Nefrologia', estatus: 'A');
	Servicio.create(codigo: 'SER-7', especialidad_id: 7, nombre: 'Consulta Medica en Neurologia', estatus: 'A');
	Servicio.create(codigo: 'SER-8', especialidad_id: 8, nombre: 'Consulta Medica en Nutriologia', estatus: 'A');
	Servicio.create(codigo: 'SER-9', especialidad_id: 9, nombre: 'Consulta Medica en Oftalmologia', estatus: 'A');
	Servicio.create(codigo: 'SER-10', especialidad_id: 10, nombre: 'Consulta Medica en Urologia', estatus: 'A');

	Servicio.create(codigo: 'SER-11', especialidad_id: 11, nombre: 'Examen de Analisis de Sangre', estatus: 'A');
	Servicio.create(codigo: 'SER-12', especialidad_id: 12, nombre: 'Examen de Analisis de Orina', estatus: 'A');
	Servicio.create(codigo: 'SER-13', especialidad_id: 13, nombre: 'Examen de Analisis de Heces', estatus: 'A');
	Servicio.create(codigo: 'SER-14', especialidad_id: 14, nombre: 'Examen de Colesterol', estatus: 'A');
	Servicio.create(codigo: 'SER-15', especialidad_id: 15, nombre: 'Examen de Glucosa', estatus: 'A');
	Servicio.create(codigo: 'SER-16', especialidad_id: 16, nombre: 'Examen de Transaminasas', estatus: 'A');
	Servicio.create(codigo: 'SER-17', especialidad_id: 17, nombre: 'Examen de Hemograma', estatus: 'A');

	Servicio.create(codigo: 'SER-18', especialidad_id: 18, nombre: 'Radiografia de la Pelvis', estatus: 'A');
	Servicio.create(codigo: 'SER-19', especialidad_id: 18, nombre: 'Rediografia de Torax', estatus: 'A');
	Servicio.create(codigo: 'SER-20', especialidad_id: 18, nombre: 'Radiografia Abdominal', estatus: 'A');
	Servicio.create(codigo: 'SER-21', especialidad_id: 18, nombre: 'Radiografia de Hueso', estatus: 'A');
	Servicio.create(codigo: 'SER-22', especialidad_id: 18, nombre: 'Radiografia de los Dientes', estatus: 'A');
	Servicio.create(codigo: 'SER-23', especialidad_id: 18, nombre: 'Radiografia de las Articulaciones', estatus: 'A');
	Servicio.create(codigo: 'SER-24', especialidad_id: 18, nombre: 'Radiografia del Cuello', estatus: 'A');
	Servicio.create(codigo: 'SER-25', especialidad_id: 18, nombre: 'Radiografia del Craneo', estatus: 'A');
	Servicio.create(codigo: 'SER-26', especialidad_id: 18, nombre: 'Radiografia de la Columna Toracica', estatus: 'A');
	Servicio.create(codigo: 'SER-27', especialidad_id: 18, nombre: 'Radiografia de Mano', estatus: 'A');

	Servicio.create(codigo: 'SER-28', especialidad_id: 19, nombre: 'Tomografia de Torax', estatus: 'A');
	Servicio.create(codigo: 'SER-29', especialidad_id: 19, nombre: 'Tomografia del Craneo', estatus: 'A');
	Servicio.create(codigo: 'SER-30', especialidad_id: 19, nombre: 'Tomografia del Abdomen y la Pelvis ', estatus: 'A');
	Servicio.create(codigo: 'SER-31', especialidad_id: 19, nombre: 'Tomografia de la Orbita', estatus: 'A');
	Servicio.create(codigo: 'SER-32', especialidad_id: 19, nombre: 'Tomografia de la Columna lumbosacra, servical y toracica', estatus: 'A');

	Servicio.create(codigo: 'SER-33', especialidad_id: 20, nombre: 'Ecografia abdominal', estatus: 'A');
	Servicio.create(codigo: 'SER-34', especialidad_id: 20, nombre: 'Ecografia vaginal', estatus: 'A');
	Servicio.create(codigo: 'SER-35', especialidad_id: 20, nombre: 'Ecografia de mama', estatus: 'A');
	Servicio.create(codigo: 'SER-36', especialidad_id: 20, nombre: 'Ecografia Doppler', estatus: 'A');
	Servicio.create(codigo: 'SER-37', especialidad_id: 20, nombre: 'Ecografia 3D y 4D', estatus: 'A');
	Servicio.create(codigo: 'SER-38', especialidad_id: 20, nombre: 'Ecografia cutanea', estatus: 'A');

	Servicio.create(codigo: 'SER-39', especialidad_id: 21, nombre: 'Mamografia tradicional', estatus: 'A');
	Servicio.create(codigo: 'SER-40', especialidad_id: 21, nombre: 'Mamografia digital', estatus: 'A');

	Servicio.create(codigo: 'SER-41', especialidad_id: 22, nombre: 'Resonancia Magnetica del abdomen', estatus: 'A');
	Servicio.create(codigo: 'SER-42', especialidad_id: 22, nombre: 'Resonancia Magnetica cervical', estatus: 'A');
	Servicio.create(codigo: 'SER-43', especialidad_id: 22, nombre: 'Resonancia Magnetica del torax', estatus: 'A');
	Servicio.create(codigo: 'SER-44', especialidad_id: 22, nombre: 'Resonancia Magnetica del craneo', estatus: 'A');
	Servicio.create(codigo: 'SER-45', especialidad_id: 22, nombre: 'Resonancia Magnetica del corazon', estatus: 'A');
	Servicio.create(codigo: 'SER-46', especialidad_id: 22, nombre: 'Resonancia Magnetica lumbar', estatus: 'A');
	Servicio.create(codigo: 'SER-47', especialidad_id: 22, nombre: 'Resonancia Magnetica pelvica', estatus: 'A');

	Especialista.create(codigo: 'EPA-1', nombre: 'Pedro Camacaro', descripcion: 'Graduado en la UCLA, cuenta con 15 años de experiencia y ha trabajado en diversos Hospitales del pais y del mundo', estatus: 'A');
	Especialista.create(codigo: 'EPA-2', nombre: 'Pedro Camacaro', descripcion: 'Graduado en la UCLA, cuenta con 15 años de experiencia y ha trabajado en diversos Hospitales del pais y del mundo', estatus: 'A');
	Especialista.create(codigo: 'EPA-3', nombre: 'Pedro Camacaro', descripcion: 'Graduado en la UCLA, cuenta con 15 años de experiencia y ha trabajado en diversos Hospitales del pais y del mundo', estatus: 'A');
	Especialista.create(codigo: 'EPA-4', nombre: 'Pedro Camacaro', descripcion: 'Graduado en la UCLA, cuenta con 15 años de experiencia y ha trabajado en diversos Hospitales del pais y del mundo', estatus: 'A');
	Especialista.create(codigo: 'EPA-5', nombre: 'Pedro Camacaro', descripcion: 'Graduado en la UCLA, cuenta con 15 años de experiencia y ha trabajado en diversos Hospitales del pais y del mundo', estatus: 'A');
	Especialista.create(codigo: 'EPA-6', nombre: 'Pedro Camacaro', descripcion: 'Graduado en la UCLA, cuenta con 15 años de experiencia y ha trabajado en diversos Hospitales del pais y del mundo', estatus: 'A');

	Especialista.create(codigo: 'EPA-7', nombre: 'Pedro Camacaro', descripcion: 'Graduado en la UCLA, cuenta con 15 años de experiencia y ha trabajado en diversos Hospitales del pais y del mundo', estatus: 'A');
	Especialista.create(codigo: 'EPA-8', nombre: 'Pedro Camacaro', descripcion: 'Graduado en la UCLA, cuenta con 15 años de experiencia y ha trabajado en diversos Hospitales del pais y del mundo', estatus: 'A');
	Especialista.create(codigo: 'EPA-9', nombre: 'Pedro Camacaro', descripcion: 'Graduado en la UCLA, cuenta con 15 años de experiencia y ha trabajado en diversos Hospitales del pais y del mundo', estatus: 'A');
	Especialista.create(codigo: 'EPA-10', nombre: 'Pedro Camacaro', descripcion: 'Graduado en la UCLA, cuenta con 15 años de experiencia y ha trabajado en diversos Hospitales del pais y del mundo', estatus: 'A');
	Especialista.create(codigo: 'EPA-11', nombre: 'Pedro Camacaro', descripcion: 'Graduado en la UCLA, cuenta con 15 años de experiencia y ha trabajado en diversos Hospitales del pais y del mundo', estatus: 'A');
	Especialista.create(codigo: 'EPA-12', nombre: 'Pedro Camacaro', descripcion: 'Graduado en la UCLA, cuenta con 15 años de experiencia y ha trabajado en diversos Hospitales del pais y del mundo', estatus: 'A');

	Especialista.create(codigo: 'EPA-13', nombre: 'Pedro Camacaro', descripcion: 'Graduado en la UCLA, cuenta con 15 años de experiencia y ha trabajado en diversos Hospitales del pais y del mundo', estatus: 'A');
	Especialista.create(codigo: 'EPA-14', nombre: 'Pedro Camacaro', descripcion: 'Graduado en la UCLA, cuenta con 15 años de experiencia y ha trabajado en diversos Hospitales del pais y del mundo', estatus: 'A');
	Especialista.create(codigo: 'EPA-15', nombre: 'Pedro Camacaro', descripcion: 'Graduado en la UCLA, cuenta con 15 años de experiencia y ha trabajado en diversos Hospitales del pais y del mundo', estatus: 'A');
	Especialista.create(codigo: 'EPA-16', nombre: 'Pedro Camacaro', descripcion: 'Graduado en la UCLA, cuenta con 15 años de experiencia y ha trabajado en diversos Hospitales del pais y del mundo', estatus: 'A');
	Especialista.create(codigo: 'EPA-17', nombre: 'Pedro Camacaro', descripcion: 'Graduado en la UCLA, cuenta con 15 años de experiencia y ha trabajado en diversos Hospitales del pais y del mundo', estatus: 'A');
	Especialista.create(codigo: 'EPA-18', nombre: 'Pedro Camacaro', descripcion: 'Graduado en la UCLA, cuenta con 15 años de experiencia y ha trabajado en diversos Hospitales del pais y del mundo', estatus: 'A');

	Especialista.create(codigo: 'EPA-19', nombre: 'Pedro Camacaro', descripcion: 'Graduado en la UCLA, cuenta con 15 años de experiencia y ha trabajado en diversos Hospitales del pais y del mundo', estatus: 'A');
	Especialista.create(codigo: 'EPA-20', nombre: 'Pedro Camacaro', descripcion: 'Graduado en la UCLA, cuenta con 15 años de experiencia y ha trabajado en diversos Hospitales del pais y del mundo', estatus: 'A');
	Especialista.create(codigo: 'EPA-21', nombre: 'Pedro Camacaro', descripcion: 'Graduado en la UCLA, cuenta con 15 años de experiencia y ha trabajado en diversos Hospitales del pais y del mundo', estatus: 'A');
	Especialista.create(codigo: 'EPA-22', nombre: 'Pedro Camacaro', descripcion: 'Graduado en la UCLA, cuenta con 15 años de experiencia y ha trabajado en diversos Hospitales del pais y del mundo', estatus: 'A');
	Especialista.create(codigo: 'EPA-23', nombre: 'Pedro Camacaro', descripcion: 'Graduado en la UCLA, cuenta con 15 años de experiencia y ha trabajado en diversos Hospitales del pais y del mundo', estatus: 'A');
	Especialista.create(codigo: 'EPA-24', nombre: 'Pedro Camacaro', descripcion: 'Graduado en la UCLA, cuenta con 15 años de experiencia y ha trabajado en diversos Hospitales del pais y del mundo', estatus: 'A');

	Especialista.create(codigo: 'EPA-25', nombre: 'Pedro Camacaro', descripcion: 'Graduado en la UCLA, cuenta con 15 años de experiencia y ha trabajado en diversos Hospitales del pais y del mundo', estatus: 'A');
	Especialista.create(codigo: 'EPA-26', nombre: 'Pedro Camacaro', descripcion: 'Graduado en la UCLA, cuenta con 15 años de experiencia y ha trabajado en diversos Hospitales del pais y del mundo', estatus: 'A');
	Especialista.create(codigo: 'EPA-27', nombre: 'Pedro Camacaro', descripcion: 'Graduado en la UCLA, cuenta con 15 años de experiencia y ha trabajado en diversos Hospitales del pais y del mundo', estatus: 'A');
	Especialista.create(codigo: 'EPA-28', nombre: 'Pedro Camacaro', descripcion: 'Graduado en la UCLA, cuenta con 15 años de experiencia y ha trabajado en diversos Hospitales del pais y del mundo', estatus: 'A');
	Especialista.create(codigo: 'EPA-29', nombre: 'Pedro Camacaro', descripcion: 'Graduado en la UCLA, cuenta con 15 años de experiencia y ha trabajado en diversos Hospitales del pais y del mundo', estatus: 'A');
	Especialista.create(codigo: 'EPA-30', nombre: 'Pedro Camacaro', descripcion: 'Graduado en la UCLA, cuenta con 15 años de experiencia y ha trabajado en diversos Hospitales del pais y del mundo', estatus: 'A');

	Especialista.create(codigo: 'EPA-31', nombre: 'Pedro Camacaro', descripcion: 'Graduado en la UCLA, cuenta con 15 años de experiencia y ha trabajado en diversos Hospitales del pais y del mundo', estatus: 'A');
	Especialista.create(codigo: 'EPA-32', nombre: 'Pedro Camacaro', descripcion: 'Graduado en la UCLA, cuenta con 15 años de experiencia y ha trabajado en diversos Hospitales del pais y del mundo', estatus: 'A');
	Especialista.create(codigo: 'EPA-33', nombre: 'Pedro Camacaro', descripcion: 'Graduado en la UCLA, cuenta con 15 años de experiencia y ha trabajado en diversos Hospitales del pais y del mundo', estatus: 'A');
	Especialista.create(codigo: 'EPA-34', nombre: 'Pedro Camacaro', descripcion: 'Graduado en la UCLA, cuenta con 15 años de experiencia y ha trabajado en diversos Hospitales del pais y del mundo', estatus: 'A');
	Especialista.create(codigo: 'EPA-35', nombre: 'Pedro Camacaro', descripcion: 'Graduado en la UCLA, cuenta con 15 años de experiencia y ha trabajado en diversos Hospitales del pais y del mundo', estatus: 'A');
	Especialista.create(codigo: 'EPA-36', nombre: 'Pedro Camacaro', descripcion: 'Graduado en la UCLA, cuenta con 15 años de experiencia y ha trabajado en diversos Hospitales del pais y del mundo', estatus: 'A');

	Especialista.create(codigo: 'EPA-37', nombre: 'Pedro Camacaro', descripcion: 'Graduado en la UCLA, cuenta con 15 años de experiencia y ha trabajado en diversos Hospitales del pais y del mundo', estatus: 'A');
	Especialista.create(codigo: 'EPA-38', nombre: 'Pedro Camacaro', descripcion: 'Graduado en la UCLA, cuenta con 15 años de experiencia y ha trabajado en diversos Hospitales del pais y del mundo', estatus: 'A');
	Especialista.create(codigo: 'EPA-39', nombre: 'Pedro Camacaro', descripcion: 'Graduado en la UCLA, cuenta con 15 años de experiencia y ha trabajado en diversos Hospitales del pais y del mundo', estatus: 'A');
	Especialista.create(codigo: 'EPA-40', nombre: 'Pedro Camacaro', descripcion: 'Graduado en la UCLA, cuenta con 15 años de experiencia y ha trabajado en diversos Hospitales del pais y del mundo', estatus: 'A');
	Especialista.create(codigo: 'EPA-41', nombre: 'Pedro Camacaro', descripcion: 'Graduado en la UCLA, cuenta con 15 años de experiencia y ha trabajado en diversos Hospitales del pais y del mundo', estatus: 'A');
	Especialista.create(codigo: 'EPA-42', nombre: 'Pedro Camacaro', descripcion: 'Graduado en la UCLA, cuenta con 15 años de experiencia y ha trabajado en diversos Hospitales del pais y del mundo', estatus: 'A');

	Especialista.create(codigo: 'EPA-43', nombre: 'Pedro Camacaro', descripcion: 'Graduado en la UCLA, cuenta con 15 años de experiencia y ha trabajado en diversos Hospitales del pais y del mundo', estatus: 'A');
	Especialista.create(codigo: 'EPA-44', nombre: 'Pedro Camacaro', descripcion: 'Graduado en la UCLA, cuenta con 15 años de experiencia y ha trabajado en diversos Hospitales del pais y del mundo', estatus: 'A');
	Especialista.create(codigo: 'EPA-45', nombre: 'Pedro Camacaro', descripcion: 'Graduado en la UCLA, cuenta con 15 años de experiencia y ha trabajado en diversos Hospitales del pais y del mundo', estatus: 'A');
	Especialista.create(codigo: 'EPA-46', nombre: 'Pedro Camacaro', descripcion: 'Graduado en la UCLA, cuenta con 15 años de experiencia y ha trabajado en diversos Hospitales del pais y del mundo', estatus: 'A');
	Especialista.create(codigo: 'EPA-47', nombre: 'Pedro Camacaro', descripcion: 'Graduado en la UCLA, cuenta con 15 años de experiencia y ha trabajado en diversos Hospitales del pais y del mundo', estatus: 'A');
	Especialista.create(codigo: 'EPA-48', nombre: 'Pedro Camacaro', descripcion: 'Graduado en la UCLA, cuenta con 15 años de experiencia y ha trabajado en diversos Hospitales del pais y del mundo', estatus: 'A');

	Especialista.create(codigo: 'EPA-49', nombre: 'Pedro Camacaro', descripcion: 'Graduado en la UCLA, cuenta con 15 años de experiencia y ha trabajado en diversos Hospitales del pais y del mundo', estatus: 'A');
	Especialista.create(codigo: 'EPA-50', nombre: 'Pedro Camacaro', descripcion: 'Graduado en la UCLA, cuenta con 15 años de experiencia y ha trabajado en diversos Hospitales del pais y del mundo', estatus: 'A');
	Especialista.create(codigo: 'EPA-51', nombre: 'Pedro Camacaro', descripcion: 'Graduado en la UCLA, cuenta con 15 años de experiencia y ha trabajado en diversos Hospitales del pais y del mundo', estatus: 'A');
	Especialista.create(codigo: 'EPA-52', nombre: 'Pedro Camacaro', descripcion: 'Graduado en la UCLA, cuenta con 15 años de experiencia y ha trabajado en diversos Hospitales del pais y del mundo', estatus: 'A');
	Especialista.create(codigo: 'EPA-53', nombre: 'Pedro Camacaro', descripcion: 'Graduado en la UCLA, cuenta con 15 años de experiencia y ha trabajado en diversos Hospitales del pais y del mundo', estatus: 'A');
	Especialista.create(codigo: 'EPA-54', nombre: 'Pedro Camacaro', descripcion: 'Graduado en la UCLA, cuenta con 15 años de experiencia y ha trabajado en diversos Hospitales del pais y del mundo', estatus: 'A');

	Especialista.create(codigo: 'EPA-55', nombre: 'Pedro Camacaro', descripcion: 'Graduado en la UCLA, cuenta con 15 años de experiencia y ha trabajado en diversos Hospitales del pais y del mundo', estatus: 'A');
	Especialista.create(codigo: 'EPA-56', nombre: 'Pedro Camacaro', descripcion: 'Graduado en la UCLA, cuenta con 15 años de experiencia y ha trabajado en diversos Hospitales del pais y del mundo', estatus: 'A');
	Especialista.create(codigo: 'EPA-57', nombre: 'Pedro Camacaro', descripcion: 'Graduado en la UCLA, cuenta con 15 años de experiencia y ha trabajado en diversos Hospitales del pais y del mundo', estatus: 'A');
	Especialista.create(codigo: 'EPA-58', nombre: 'Pedro Camacaro', descripcion: 'Graduado en la UCLA, cuenta con 15 años de experiencia y ha trabajado en diversos Hospitales del pais y del mundo', estatus: 'A');
	Especialista.create(codigo: 'EPA-59', nombre: 'Pedro Camacaro', descripcion: 'Graduado en la UCLA, cuenta con 15 años de experiencia y ha trabajado en diversos Hospitales del pais y del mundo', estatus: 'A');
	Especialista.create(codigo: 'EPA-60', nombre: 'Pedro Camacaro', descripcion: 'Graduado en la UCLA, cuenta con 15 años de experiencia y ha trabajado en diversos Hospitales del pais y del mundo', estatus: 'A');

	Especialista.create(codigo: 'EPA-61', nombre: 'Faes Rodriguez', descripcion: 'Graduado en la UCLA, cuenta con 15 años de experiencia y ha trabajado en diversos Hospitales del pais y del mundo', estatus: 'A');
	Especialista.create(codigo: 'EPA-62', nombre: 'Faes Rodriguez', descripcion: 'Graduado en la UCLA, cuenta con 15 años de experiencia y ha trabajado en diversos Hospitales del pais y del mundo', estatus: 'A');
	Especialista.create(codigo: 'EPA-63', nombre: 'Faes Rodriguez', descripcion: 'Graduado en la UCLA, cuenta con 15 años de experiencia y ha trabajado en diversos Hospitales del pais y del mundo', estatus: 'A');

	Especialista.create(codigo: 'EPA-64', nombre: 'Faes Rodriguez', descripcion: 'Graduado en la UCLA, cuenta con 15 años de experiencia y ha trabajado en diversos Hospitales del pais y del mundo', estatus: 'A');
	Especialista.create(codigo: 'EPA-65', nombre: 'Faes Rodriguez', descripcion: 'Graduado en la UCLA, cuenta con 15 años de experiencia y ha trabajado en diversos Hospitales del pais y del mundo', estatus: 'A');
	Especialista.create(codigo: 'EPA-66', nombre: 'Faes Rodriguez', descripcion: 'Graduado en la UCLA, cuenta con 15 años de experiencia y ha trabajado en diversos Hospitales del pais y del mundo', estatus: 'A');

	Especialista.create(codigo: 'EPA-67', nombre: 'Faes Rodriguez', descripcion: 'Graduado en la UCLA, cuenta con 15 años de experiencia y ha trabajado en diversos Hospitales del pais y del mundo', estatus: 'A');
	Especialista.create(codigo: 'EPA-68', nombre: 'Faes Rodriguez', descripcion: 'Graduado en la UCLA, cuenta con 15 años de experiencia y ha trabajado en diversos Hospitales del pais y del mundo', estatus: 'A');
	Especialista.create(codigo: 'EPA-69', nombre: 'Faes Rodriguez', descripcion: 'Graduado en la UCLA, cuenta con 15 años de experiencia y ha trabajado en diversos Hospitales del pais y del mundo', estatus: 'A');

	Especialista.create(codigo: 'EPA-70', nombre: 'Faes Rodriguez', descripcion: 'Graduado en la UCLA, cuenta con 15 años de experiencia y ha trabajado en diversos Hospitales del pais y del mundo', estatus: 'A');
	Especialista.create(codigo: 'EPA-71', nombre: 'Faes Rodriguez', descripcion: 'Graduado en la UCLA, cuenta con 15 años de experiencia y ha trabajado en diversos Hospitales del pais y del mundo', estatus: 'A');
	Especialista.create(codigo: 'EPA-72', nombre: 'Faes Rodriguez', descripcion: 'Graduado en la UCLA, cuenta con 15 años de experiencia y ha trabajado en diversos Hospitales del pais y del mundo', estatus: 'A');

	Especialista.create(codigo: 'EPA-73', nombre: 'Faes Rodriguez', descripcion: 'Graduado en la UCLA, cuenta con 15 años de experiencia y ha trabajado en diversos Hospitales del pais y del mundo', estatus: 'A');
	Especialista.create(codigo: 'EPA-74', nombre: 'Faes Rodriguez', descripcion: 'Graduado en la UCLA, cuenta con 15 años de experiencia y ha trabajado en diversos Hospitales del pais y del mundo', estatus: 'A');
	Especialista.create(codigo: 'EPA-75', nombre: 'Faes Rodriguez', descripcion: 'Graduado en la UCLA, cuenta con 15 años de experiencia y ha trabajado en diversos Hospitales del pais y del mundo', estatus: 'A');

	Especialista.create(codigo: 'EPA-76', nombre: 'Faes Rodriguez', descripcion: 'Graduado en la UCLA, cuenta con 15 años de experiencia y ha trabajado en diversos Hospitales del pais y del mundo', estatus: 'A');
	Especialista.create(codigo: 'EPA-77', nombre: 'Faes Rodriguez', descripcion: 'Graduado en la UCLA, cuenta con 15 años de experiencia y ha trabajado en diversos Hospitales del pais y del mundo', estatus: 'A');
	Especialista.create(codigo: 'EPA-78', nombre: 'Faes Rodriguez', descripcion: 'Graduado en la UCLA, cuenta con 15 años de experiencia y ha trabajado en diversos Hospitales del pais y del mundo', estatus: 'A');

	Especialista.create(codigo: 'EPA-79', nombre: 'Faes Rodriguez', descripcion: 'Graduado en la UCLA, cuenta con 15 años de experiencia y ha trabajado en diversos Hospitales del pais y del mundo', estatus: 'A');
	Especialista.create(codigo: 'EPA-80', nombre: 'Faes Rodriguez', descripcion: 'Graduado en la UCLA, cuenta con 15 años de experiencia y ha trabajado en diversos Hospitales del pais y del mundo', estatus: 'A');
	Especialista.create(codigo: 'EPA-81', nombre: 'Faes Rodriguez', descripcion: 'Graduado en la UCLA, cuenta con 15 años de experiencia y ha trabajado en diversos Hospitales del pais y del mundo', estatus: 'A');

	Especialista.create(codigo: 'EPA-82', nombre: 'Carlos Castillo', descripcion: 'Graduado en la UCLA, cuenta con 15 años de experiencia y ha trabajado en diversos Hospitales del pais y del mundo', estatus: 'A');
	Especialista.create(codigo: 'EPA-83', nombre: 'Ericka Muñoz', descripcion: 'Graduado en la UCLA, cuenta con 15 años de experiencia y ha trabajado en diversos Hospitales del pais y del mundo', estatus: 'A');
	Especialista.create(codigo: 'EPA-84', nombre: 'Ericksoon Muñoz', descripcion: 'Graduado en la UCLA, cuenta con 15 años de experiencia y ha trabajado en diversos Hospitales del pais y del mundo', estatus: 'A');
	Especialista.create(codigo: 'EPA-85', nombre: 'Jesus Olivera', descripcion: 'Graduado en la UCLA, cuenta con 15 años de experiencia y ha trabajado en diversos Hospitales del pais y del mundo', estatus: 'A');
	Especialista.create(codigo: 'EPA-86', nombre: 'Cesar Jesus', descripcion: 'Graduado en la UCLA, cuenta con 15 años de experiencia y ha trabajado en diversos Hospitales del pais y del mundo', estatus: 'A');
	Especialista.create(codigo: 'EPA-87', nombre: 'Jesus Oviedo', descripcion: 'Graduado en la UCLA, cuenta con 15 años de experiencia y ha trabajado en diversos Hospitales del pais y del mundo', estatus: 'A');
	Especialista.create(codigo: 'EPA-88', nombre: 'Alexis Alonso', descripcion: 'Graduado en la UCLA, cuenta con 15 años de experiencia y ha trabajado en diversos Hospitales del pais y del mundo', estatus: 'A');
	Especialista.create(codigo: 'EPA-89', nombre: 'Juan Changir', descripcion: 'Graduado en la UCLA, cuenta con 15 años de experiencia y ha trabajado en diversos Hospitales del pais y del mundo', estatus: 'A');
	Especialista.create(codigo: 'EPA-90', nombre: 'Synahi Castillo', descripcion: 'Graduado en la UCLA, cuenta con 15 años de experiencia y ha trabajado en diversos Hospitales del pais y del mundo', estatus: 'A');
	Especialista.create(codigo: 'EPA-91', nombre: 'Rayda Rodriguez', descripcion: 'Graduado en la UCLA, cuenta con 15 años de experiencia y ha trabajado en diversos Hospitales del pais y del mundo', estatus: 'A');
	Especialista.create(codigo: 'EPA-92', nombre: 'Emily Chirinos', descripcion: 'Graduado en la UCLA, cuenta con 15 años de experiencia y ha trabajado en diversos Hospitales del pais y del mundo', estatus: 'A');
	Especialista.create(codigo: 'EPA-93', nombre: 'Elgymar Garcia', descripcion: 'Graduado en la UCLA, cuenta con 15 años de experiencia y ha trabajado en diversos Hospitales del pais y del mundo', estatus: 'A');
	Especialista.create(codigo: 'EPA-94', nombre: 'Estefania Montesdeoca', descripcion: 'Graduado en la UCLA, cuenta con 15 años de experiencia y ha trabajado en diversos Hospitales del pais y del mundo', estatus: 'A');
	Especialista.create(codigo: 'EPA-95', nombre: 'Genesis Camacaro', descripcion: 'Graduado en la UCLA, cuenta con 15 años de experiencia y ha trabajado en diversos Hospitales del pais y del mundo', estatus: 'A');
	Especialista.create(codigo: 'EPA-96', nombre: 'Maria Fernanda Reinoso', descripcion: 'Graduado en la UCLA, cuenta con 15 años de experiencia y ha trabajado en diversos Hospitales del pais y del mundo', estatus: 'A');
	Especialista.create(codigo: 'EPA-97', nombre: 'Jose Orozco', descripcion: 'Graduado en la UCLA, cuenta con 15 años de experiencia y ha trabajado en diversos Hospitales del pais y del mundo', estatus: 'A');
	Especialista.create(codigo: 'EPA-98', nombre: 'Andrea Orozco', descripcion: 'Graduado en la UCLA, cuenta con 15 años de experiencia y ha trabajado en diversos Hospitales del pais y del mundo', estatus: 'A');
	Especialista.create(codigo: 'EPA-99', nombre: 'Greily Marmol', descripcion: 'Graduado en la UCLA, cuenta con 15 años de experiencia y ha trabajado en diversos Hospitales del pais y del mundo', estatus: 'A');

	EspecialistaServicio.create(codigo: 'ESS-1', especialista_id: 1, servicio_id: 1, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-2', especialista_id: 2, servicio_id: 1, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-3', especialista_id: 3, servicio_id: 1, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-4', especialista_id: 4, servicio_id: 1, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-5', especialista_id: 5, servicio_id: 1, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-6', especialista_id: 6, servicio_id: 1, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-7', especialista_id: 7, servicio_id: 2, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-8', especialista_id: 8, servicio_id: 2, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-9', especialista_id: 9, servicio_id: 2, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-10', especialista_id: 10, servicio_id: 2, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-11', especialista_id: 11, servicio_id: 2, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-12', especialista_id: 12, servicio_id: 2, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-13', especialista_id: 13, servicio_id: 3, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-14', especialista_id: 14, servicio_id: 3, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-15', especialista_id: 15, servicio_id: 3, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-16', especialista_id: 16, servicio_id: 3, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-17', especialista_id: 17, servicio_id: 3, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-18', especialista_id: 18, servicio_id: 3, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-19', especialista_id: 19, servicio_id: 4, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-20', especialista_id: 20, servicio_id: 4, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-21', especialista_id: 21, servicio_id: 4, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-22', especialista_id: 22, servicio_id: 4, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-23', especialista_id: 23, servicio_id: 4, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-24', especialista_id: 24, servicio_id: 4, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-25', especialista_id: 25, servicio_id: 5, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-26', especialista_id: 26, servicio_id: 5, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-27', especialista_id: 27, servicio_id: 5, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-28', especialista_id: 28, servicio_id: 5, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-29', especialista_id: 29, servicio_id: 5, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-30', especialista_id: 30, servicio_id: 5, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-31', especialista_id: 31, servicio_id: 6, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-32', especialista_id: 32, servicio_id: 6, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-33', especialista_id: 33, servicio_id: 6, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-34', especialista_id: 34, servicio_id: 6, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-35', especialista_id: 35, servicio_id: 6, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-36', especialista_id: 36, servicio_id: 6, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-37', especialista_id: 37, servicio_id: 7, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-38', especialista_id: 38, servicio_id: 7, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-39', especialista_id: 39, servicio_id: 7, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-40', especialista_id: 40, servicio_id: 7, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-41', especialista_id: 41, servicio_id: 7, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-42', especialista_id: 42, servicio_id: 7, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-43', especialista_id: 43, servicio_id: 8, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-44', especialista_id: 44, servicio_id: 8, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-45', especialista_id: 45, servicio_id: 8, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-46', especialista_id: 46, servicio_id: 8, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-47', especialista_id: 47, servicio_id: 8, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-48', especialista_id: 48, servicio_id: 8, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-49', especialista_id: 49, servicio_id: 9, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-50', especialista_id: 50, servicio_id: 9, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-51', especialista_id: 51, servicio_id: 9, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-52', especialista_id: 52, servicio_id: 9, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-53', especialista_id: 53, servicio_id: 9, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-54', especialista_id: 54, servicio_id: 9, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-55', especialista_id: 55, servicio_id: 10, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-56', especialista_id: 56, servicio_id: 10, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-57', especialista_id: 57, servicio_id: 10, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-58', especialista_id: 58, servicio_id: 10, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-59', especialista_id: 59, servicio_id: 10, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-60', especialista_id: 60, servicio_id: 10, estatus: 'A');

	EspecialistaServicio.create(codigo: 'ESS-61', especialista_id: 61, servicio_id: 11, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-62', especialista_id: 62, servicio_id: 11, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-63', especialista_id: 63, servicio_id: 11, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-64', especialista_id: 64, servicio_id: 12, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-65', especialista_id: 65, servicio_id: 12, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-66', especialista_id: 66, servicio_id: 12, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-67', especialista_id: 67, servicio_id: 13, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-68', especialista_id: 68, servicio_id: 13, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-69', especialista_id: 69, servicio_id: 13, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-70', especialista_id: 70, servicio_id: 14, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-71', especialista_id: 71, servicio_id: 14, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-72', especialista_id: 72, servicio_id: 14, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-73', especialista_id: 73, servicio_id: 15, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-74', especialista_id: 74, servicio_id: 15, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-75', especialista_id: 75, servicio_id: 15, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-76', especialista_id: 76, servicio_id: 16, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-77', especialista_id: 77, servicio_id: 16, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-78', especialista_id: 78, servicio_id: 16, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-79', especialista_id: 79, servicio_id: 17, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-80', especialista_id: 80, servicio_id: 17, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-81', especialista_id: 81, servicio_id: 17, estatus: 'A');

	EspecialistaServicio.create(codigo: 'ESS-82', especialista_id: 82, servicio_id: 19, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-83', especialista_id: 83, servicio_id: 19, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-84', especialista_id: 84, servicio_id: 19, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-85', especialista_id: 85, servicio_id: 19, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-86', especialista_id: 82, servicio_id: 20, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-87', especialista_id: 83, servicio_id: 20, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-88', especialista_id: 84, servicio_id: 20, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-89', especialista_id: 85, servicio_id: 20, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-90', especialista_id: 82, servicio_id: 21, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-91', especialista_id: 83, servicio_id: 21, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-92', especialista_id: 84, servicio_id: 21, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-93', especialista_id: 85, servicio_id: 21, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-94', especialista_id: 82, servicio_id: 22, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-95', especialista_id: 83, servicio_id: 22, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-96', especialista_id: 84, servicio_id: 22, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-97', especialista_id: 85, servicio_id: 22, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-98', especialista_id: 82, servicio_id: 23, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-99', especialista_id: 83, servicio_id: 23, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-100', especialista_id: 84, servicio_id: 23, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-101', especialista_id: 85, servicio_id: 23, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-102', especialista_id: 82, servicio_id: 24, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-103', especialista_id: 83, servicio_id: 24, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-104', especialista_id: 84, servicio_id: 24, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-105', especialista_id: 85, servicio_id: 24, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-106', especialista_id: 82, servicio_id: 25, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-107', especialista_id: 83, servicio_id: 25, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-108', especialista_id: 84, servicio_id: 25, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-109', especialista_id: 85, servicio_id: 25, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-110', especialista_id: 82, servicio_id: 26, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-111', especialista_id: 83, servicio_id: 26, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-112', especialista_id: 84, servicio_id: 26, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-113', especialista_id: 85, servicio_id: 26, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-114', especialista_id: 82, servicio_id: 27, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-115', especialista_id: 83, servicio_id: 27, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-116', especialista_id: 84, servicio_id: 27, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-117', especialista_id: 85, servicio_id: 27, estatus: 'A'); 

	EspecialistaServicio.create(codigo: 'ESS-118', especialista_id: 86, servicio_id: 28, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-119', especialista_id: 87, servicio_id: 28, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-120', especialista_id: 88, servicio_id: 28, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-121', especialista_id: 89, servicio_id: 28, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-122', especialista_id: 86, servicio_id: 29, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-123', especialista_id: 87, servicio_id: 29, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-124', especialista_id: 88, servicio_id: 29, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-125', especialista_id: 89, servicio_id: 29, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-126', especialista_id: 86, servicio_id: 30, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-127', especialista_id: 87, servicio_id: 30, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-128', especialista_id: 88, servicio_id: 30, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-129', especialista_id: 89, servicio_id: 30, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-130', especialista_id: 86, servicio_id: 31, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-131', especialista_id: 87, servicio_id: 31, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-132', especialista_id: 88, servicio_id: 31, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-133', especialista_id: 89, servicio_id: 31, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-134', especialista_id: 86, servicio_id: 32, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-135', especialista_id: 87, servicio_id: 32, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-136', especialista_id: 88, servicio_id: 32, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-137', especialista_id: 89, servicio_id: 32, estatus: 'A');

	EspecialistaServicio.create(codigo: 'ESS-138', especialista_id: 90, servicio_id: 33, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-139', especialista_id: 91, servicio_id: 33, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-140', especialista_id: 92, servicio_id: 33, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-141', especialista_id: 93, servicio_id: 33, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-142', especialista_id: 90, servicio_id: 34, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-143', especialista_id: 91, servicio_id: 34, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-144', especialista_id: 92, servicio_id: 34, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-145', especialista_id: 93, servicio_id: 34, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-146', especialista_id: 90, servicio_id: 35, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-147', especialista_id: 91, servicio_id: 35, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-148', especialista_id: 92, servicio_id: 35, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-149', especialista_id: 93, servicio_id: 35, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-150', especialista_id: 90, servicio_id: 36, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-151', especialista_id: 91, servicio_id: 36, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-152', especialista_id: 92, servicio_id: 36, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-153', especialista_id: 93, servicio_id: 36, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-154', especialista_id: 90, servicio_id: 37, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-155', especialista_id: 91, servicio_id: 37, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-156', especialista_id: 92, servicio_id: 37, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-157', especialista_id: 93, servicio_id: 37, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-158', especialista_id: 90, servicio_id: 38, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-159', especialista_id: 91, servicio_id: 38, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-160', especialista_id: 92, servicio_id: 38, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-161', especialista_id: 93, servicio_id: 38, estatus: 'A'); 

	EspecialistaServicio.create(codigo: 'ESS-162', especialista_id: 94, servicio_id: 39, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-163', especialista_id: 95, servicio_id: 39, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-164', especialista_id: 94, servicio_id: 40, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-165', especialista_id: 95, servicio_id: 40, estatus: 'A'); 

	EspecialistaServicio.create(codigo: 'ESS-166', especialista_id: 96, servicio_id: 41, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-167', especialista_id: 97, servicio_id: 41, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-168', especialista_id: 98, servicio_id: 41, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-169', especialista_id: 99, servicio_id: 41, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-170', especialista_id: 96, servicio_id: 42, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-171', especialista_id: 97, servicio_id: 42, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-172', especialista_id: 98, servicio_id: 42, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-173', especialista_id: 99, servicio_id: 42, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-174', especialista_id: 96, servicio_id: 43, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-175', especialista_id: 97, servicio_id: 43, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-176', especialista_id: 98, servicio_id: 43, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-177', especialista_id: 99, servicio_id: 43, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-178', especialista_id: 96, servicio_id: 44, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-179', especialista_id: 97, servicio_id: 44, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-180', especialista_id: 98, servicio_id: 44, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-181', especialista_id: 99, servicio_id: 44, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-182', especialista_id: 96, servicio_id: 45, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-183', especialista_id: 97, servicio_id: 45, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-184', especialista_id: 98, servicio_id: 45, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-185', especialista_id: 99, servicio_id: 45, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-186', especialista_id: 96, servicio_id: 46, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-187', especialista_id: 97, servicio_id: 46, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-188', especialista_id: 98, servicio_id: 46, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-189', especialista_id: 99, servicio_id: 46, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-190', especialista_id: 96, servicio_id: 47, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-191', especialista_id: 97, servicio_id: 47, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-192', especialista_id: 98, servicio_id: 47, estatus: 'A');
	EspecialistaServicio.create(codigo: 'ESS-193', especialista_id: 99, servicio_id: 47, estatus: 'A');
  
  end
end
